version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'eat_beat'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'password'
      # Password for root access
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
